2025-07-25 15:33:30 | INFO     | devpulse_client.app.app:__init__:49 - Initialized DevPulse client for server: http://localhost:8000
2025-07-25 15:33:30 | INFO     | devpulse_client.app.app:start:76 - Validating credentials with server...
2025-07-25 15:33:30 | INFO     | devpulse_client.auth.collectors.device_collector:collect_fingerprint:20 - Collecting device fingerprint
2025-07-25 15:33:30 | INFO     | devpulse_client.auth.collectors.device_collector:collect_fingerprint:23 - Collecting device fingerprint: 18:60:24:92:da:75
2025-07-25 15:33:30 | INFO     | devpulse_client.auth.collectors.device_collector:collect_fingerprint:26 - Collecting device fingerprint: OKEY
2025-07-25 15:33:30 | DEBUG    | devpulse_client.auth.collectors.device_collector:collect_fingerprint:29 - Collected device fingerprint: MAC=18:60:24:92:da:75
2025-07-25 15:33:30 | ERROR    | devpulse_client.auth.client.auth_client:_send_login_request:153 - Network error: [Errno 111] Connection refused
2025-07-25 15:33:30 | ERROR    | devpulse_client.auth.client.auth_client:login:133 - Credential validation error: [Errno 111] Connection refused
2025-07-25 15:33:30 | ERROR    | devpulse_client.app.app:start:79 - ❌ None
2025-07-25 15:33:30 | ERROR    | devpulse_client.cli.commands:run:48 - ❌ Failed to start client
